apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-prod
  template:
    metadata:
      labels:
        app: sample-app-prod
    spec:
      containers:
      - name: production-deployment
        image: us-east1-docker.pkg.dev/qwiklabs-gcp-03-ca3beada462c/my-repository/sample-app-prod:v1.0
        ports:
        - containerPort: 8080
